"""Add theme_preference to User model

Revision ID: fc1b8d793938
Revises: 2cb789ad34d9
Create Date: 2025-07-13 17:40:39.267571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1b8d793938'
down_revision = '2cb789ad34d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
