#!/usr/bin/env python3
"""
Current Settings Backup - 2025-07-09
Bu dosya mevcut site ayarlarının backup'ını içerir
"""

# Mevcut ayarları içeren backup data
CURRENT_SETTINGS_BACKUP = {
    "logo2_width": 120,
    "header_show_language": False,
    "social_twitter": "@pebdeq",
    "footer_social_show_section": True,
    "homepage_products_show_rating": True,
    "products_page_show_images": True,
    "logo2_height": 40,
    "header_show_currency": False,
    "social_youtube": None,
    "footer_newsletter_title": "Newsletter",
    "homepage_products_show_quick_view": True,
    "products_page_image_height": 200,
    "header_background_color": "#999999",
    "marquee_enabled": True,
    "social_linkedin": None,
    "footer_newsletter_show_section": True,
    "homepage_products2_show_section": True,
    "products_page_image_width": 300,
    "header_text_color": "#2c3e50",
    "marquee_text": "Welcome to our store! Special offers available now.",
    "meta_title": "PEBDEQ - Craft, Vintage, Innovation",
    "footer_newsletter_description": "Subscribe to get updates about new products and offers.",
    "homepage_products2_title": "Latest Products",
    "products_page_show_favorite": True,
    "header_height": 60,
    "marquee_font_family": "Arial, sans-serif",
    "meta_description": "Discover unique 3D printed items, vintage tools, antique light bulbs, and custom laser engraving services.",
    "footer_newsletter_placeholder": "Enter your email address",
    "homepage_products2_subtitle": "Check out our newest arrivals",
    "products_page_show_buy_now": True,
    "header_padding": 10,
    "marquee_font_size": "12px",
    "meta_keywords": "3D printing, vintage tools, antique bulbs, laser engraving, custom products",
    "footer_newsletter_button_text": "Subscribe",
    "homepage_products2_max_rows": 2,
    "products_page_show_details": True,
    "header_sticky": True,
    "marquee_font_weight": "lighter",
    "currency_symbol": "$",
    "homepage_products_show_section": True,
    "homepage_products2_per_row": 4,
    "products_page_show_price": True,
    "header_shadow": True,
    "marquee_color": "#ffffff",
    "currency_code": "USD",
    "homepage_products_title": "Featured Products",
    "homepage_products2_max_items": 8,
    "products_page_show_original_price": True,
    "header_border_bottom": True,
    "marquee_background_color": "#bca9a9",
    "shipping_cost": 15.0,
    "homepage_products_subtitle": "Discover our most popular items",
    "homepage_products2_show_images": True,
    "products_page_show_stock": True,
    "header_border_color": "#eddd26",
    "marquee_speed": 30,
    "free_shipping_threshold": 200.0,
    "homepage_products_max_rows": 2,
    "homepage_products2_image_height": 200,
    "products_page_show_category": True,
    "header_logo_position": "left",
    "marquee_direction": "left",
    "enable_reviews": True,
    "homepage_products_per_row": 4,
    "homepage_products2_image_width": 300,
    "products_page_default_sort_by": "newest",
    "header_nav_position": "right",
    "marquee_pause_on_hover": True,
    "enable_wishlist": True,
    "homepage_products_max_items": 8,
    "homepage_products2_show_favorite": True,
    "products_page_card_style": "modern",
    "header_nav_spacing": 20,
    "welcome_title": "Craft, Vintage, Innovation",
    "enable_compare": True,
    "homepage_products_show_images": True,
    "homepage_products2_show_buy_now": True,
    "products_page_card_shadow": True,
    "navigation_links": [
        {
            "id": 1,
            "title": "Home",
            "url": "/",
            "enabled": True,
            "order": 1,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 2,
            "title": "Products",
            "url": "/products",
            "enabled": True,
            "order": 2,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 3,
            "title": "About",
            "url": "/about",
            "enabled": True,
            "order": 3,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 4,
            "title": "Blog",
            "url": "/blog",
            "enabled": True,
            "order": 4,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 5,
            "title": "Contact",
            "url": "/contact",
            "enabled": True,
            "order": 5,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 6,
            "title": "Login",
            "url": "/login",
            "enabled": True,
            "order": 6,
            "is_internal": True,
            "show_for": "guest",
            "type": "auth"
        },
        {
            "id": 7,
            "title": "Register",
            "url": "/register",
            "enabled": True,
            "order": 7,
            "is_internal": True,
            "show_for": "guest",
            "type": "auth"
        },
        {
            "id": 8,
            "title": "Profile",
            "url": "/profile",
            "enabled": True,
            "order": 8,
            "is_internal": True,
            "show_for": "user",
            "type": "auth"
        },
        {
            "id": 9,
            "title": "Admin",
            "url": "/admin",
            "enabled": True,
            "order": 9,
            "is_internal": True,
            "show_for": "admin",
            "type": "auth"
        },
        {
            "id": 10,
            "title": "Logout",
            "url": "logout",
            "enabled": True,
            "order": 10,
            "is_internal": True,
            "show_for": "user",
            "type": "auth"
        }
    ],
    "welcome_subtitle": "Discover unique products and custom designs",
    "enable_newsletter": True,
    "homepage_products_image_height": 200,
    "homepage_products2_show_details": True,
    "products_page_card_hover_effect": True,
    "nav_link_color": "#ffffff",
    "welcome_background_image": None,
    "maintenance_mode": False,
    "homepage_products_image_width": 300,
    "homepage_products2_show_price": True,
    "products_page_show_badges": True,
    "nav_link_hover_color": "#0f57a3",
    "welcome_background_color": "#b9b9b9",
    "footer_show_section": True,
    "homepage_products_show_favorite": True,
    "homepage_products2_show_original_price": True,
    "products_page_show_rating": True,
    "nav_link_active_color": "#007bff",
    "welcome_text_color": "#ffffff",
    "footer_background_color": "#2c3e50",
    "homepage_products_show_buy_now": True,
    "homepage_products2_show_stock": True,
    "products_page_show_quick_view": True,
    "mobile_nav_hamburger_color": "#2c3e50",
    "welcome_button_text": "Shop Now",
    "footer_text_color": "#ffffff",
    "homepage_products_show_details": True,
    "homepage_products2_show_category": True,
    "products_page_enable_pagination": True,
    "nav_link_font_size": 16,
    "welcome_button_link": "/products",
    "footer_company_name": "pebdeq",
    "homepage_products_show_price": True,
    "homepage_products2_sort_by": "newest",
    "products_page_enable_filters": True,
    "nav_link_font_weight": "500",
    "welcome_button_color": "#00b894",
    "footer_company_description": "Crafted with passion, delivered with precision.",
    "homepage_products_show_original_price": True,
    "homepage_products2_filter_categories": [],
    "products_page_enable_search": True,
    "nav_link_text_transform": "none",
    "homepage_background_color": "#e0e0e0",
    "footer_copyright_text": "© 2024 PEBDEQ. All rights reserved.",
    "homepage_products_show_stock": True,
    "homepage_products2_show_view_all": True,
    "nav_link_underline": False,
    "collections_title": "Our Collections",
    "footer_use_logo": False,
    "homepage_products_show_category": True,
    "homepage_products2_view_all_text": "View All Products",
    "nav_link_hover_effect": "color",
    "collections_show_categories": [],
    "footer_logo": None,
    "homepage_products_sort_by": "price_low",
    "homepage_products2_view_all_link": "/products",
    "site_name": "pebdeq",
    "nav_link_font_family": "'Roboto', sans-serif",
    "collections_categories_per_row": 4,
    "footer_logo_width": 120,
    "homepage_products_filter_categories": [],
    "homepage_products2_card_style": "modern",
    "nav_link_text_shadow": True,
    "collections_max_rows": 1,
    "footer_logo_height": 40,
    "homepage_products_show_view_all": True,
    "homepage_products2_card_shadow": True,
    "site_logo": None,
    "mobile_nav_enabled": True,
    "collections_show_section": True,
    "footer_support_title": "Support",
    "homepage_products_view_all_text": "View All Products",
    "homepage_products2_card_hover_effect": True,
    "use_logo": False,
    "mobile_nav_background_color": "#ffffff",
    "contact_phone": "+12223334455",
    "footer_support_show_section": True,
    "homepage_products_view_all_link": "/products",
    "homepage_products2_show_badges": True,
    "logo_width": 120,
    "mobile_nav_overlay": True,
    "contact_email": "info@pebdeq.com",
    "footer_support_links": [
        {
            "title": "Contact Us",
            "url": "/contact",
            "is_external": False
        },
        {
            "title": "FAQ",
            "url": "/faq",
            "is_external": False
        },
        {
            "title": "Shipping Info",
            "url": "/shipping",
            "is_external": False
        },
        {
            "title": "Returns",
            "url": "/returns",
            "is_external": False
        }
    ],
    "homepage_products_card_style": "modern",
    "homepage_products2_show_rating": True,
    "logo_height": 30,
    "mobile_nav_slide_direction": "left",
    "contact_address": "Virginia",
    "footer_quick_links_title": "Quick Links",
    "homepage_products_card_shadow": True,
    "homepage_products2_show_quick_view": True,
    "site_logo2": None,
    "header_show_search": False,
    "social_instagram": "@pebdeq",
    "footer_quick_links_show_section": True,
    "homepage_products_card_hover_effect": True,
    "products_page_background_color": "#e0e0e0",
    "use_logo2": False,
    "header_show_cart": False,
    "social_facebook": "pebdeq",
    "footer_quick_links": [
        {
            "is_external": False,
            "title": "About Us",
            "url": "/about"
        },
        {
            "is_external": False,
            "title": "Products",
            "url": "/products"
        },
        {
            "is_external": False,
            "title": "Blog",
            "url": "/blog"
        },
        {
            "is_external": False,
            "title": "Privacy Policy",
            "url": "/privacy"
        },
        {
            "title": "Admin",
            "url": "/admin",
            "is_external": False
        }
    ],
    "homepage_products_show_badges": True,
    "products_page_per_row": 4,
    "header_show_account": True,
    "footer_social_title": "Follow Us",
    "products_page_max_items_per_page": 12,
    
    # Footer Legal Links Section
    "footer_legal_title": "Legal",
    "footer_legal_show_section": True,
    "footer_legal_privacy_policy_title": "Privacy Policy",
    "footer_legal_privacy_policy_content": "We value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your information when you use our website and services.\n\n**Information We Collect**\n\n• Personal Information: When you create an account, make a purchase, or contact us, we may collect personal information such as your name, email address, phone number, and shipping address.\n\n• Payment Information: We collect payment details necessary to process your orders, including credit card information and billing address.\n\n• Usage Data: We automatically collect information about how you use our website, including your IP address, browser type, pages visited, and time spent on our site.\n\n**How We Use Your Information**\n\n• To process and fulfill your orders\n• To provide customer support and respond to your inquiries\n• To send you promotional emails (with your consent)\n• To improve our website and services\n• To comply with legal obligations\n\n**Information Sharing**\n\nWe do not sell, trade, or otherwise transfer your personal information to third parties except as described in this policy or with your consent.\n\n**Data Security**\n\nWe implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.\n\n**Your Rights**\n\nYou have the right to access, update, or delete your personal information. You may also opt out of receiving promotional emails at any time.\n\n**Contact Us**\n\nIf you have any questions about this Privacy Policy, please contact us at info@pebdeq.com.",
    "footer_legal_terms_of_service_title": "Terms of Service",
    "footer_legal_terms_of_service_content": "By using our website and services, you agree to comply with and be bound by these Terms of Service.\n\n**Acceptance of Terms**\n\nBy accessing and using this website, you accept and agree to be bound by the terms and provision of this agreement.\n\n**User Accounts**\n\n• You are responsible for maintaining the confidentiality of your account information\n• You must provide accurate and current information when creating an account\n• You are responsible for all activities that occur under your account\n\n**Prohibited Uses**\n\nYou may not use our website for any unlawful purpose or to:\n• Violate any applicable laws or regulations\n• Transmit harmful or malicious content\n• Attempt to gain unauthorized access to our systems\n• Interfere with the proper working of the website\n\n**Products and Services**\n\n• All products are subject to availability\n• Prices are subject to change without notice\n• We reserve the right to limit quantities\n• Product descriptions and images are for reference only\n\n**Payment Terms**\n\n• Payment is due at the time of purchase\n• We accept major credit cards and other payment methods as displayed\n• All prices are in USD unless otherwise specified\n\n**Limitation of Liability**\n\nTo the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages.\n\n**Contact Information**\n\nFor questions about these Terms of Service, please contact us at info@pebdeq.com.",
    "footer_legal_return_policy_title": "Return & Refund Policy",
    "footer_legal_return_policy_content": "We want you to be completely satisfied with your purchase. If you're not happy with your order, we're here to help.\n\n**Return Eligibility**\n\n• Items must be returned within 30 days of purchase\n• Items must be in original condition with all tags attached\n• Items must be unworn, unused, and in original packaging\n• Custom or personalized items cannot be returned unless defective\n\n**Non-Returnable Items**\n\n• Perishable goods\n• Custom or personalized products\n• Items marked as final sale\n• Used or damaged items\n• Items without original packaging\n\n**Return Process**\n\n1. Contact our customer service team at info@pebdeq.com\n2. Provide your order number and reason for return\n3. We'll provide you with a return authorization and instructions\n4. Pack items securely and ship using a trackable method\n5. Process typically takes 5-10 business days after we receive your return\n\n**Refund Processing**\n\n• Refunds will be credited to your original payment method\n• Processing time: 5-10 business days after we receive your return\n• You will receive email confirmation when refund is processed\n• Bank processing times may vary\n\n**Contact Us**\n\nFor any questions about returns or refunds, please contact us at info@pebdeq.com or call +12223334455.",
    "footer_legal_shipping_policy_title": "Shipping Policy",
    "footer_legal_shipping_policy_content": "We strive to deliver your orders quickly and safely. Please review our shipping policy for important information about delivery.\n\n**Shipping Methods**\n\n• Standard Shipping: 5-7 business days\n• Express Shipping: 2-3 business days\n• Overnight Shipping: 1 business day\n• International Shipping: 7-21 business days\n\n**Processing Time**\n\n• Orders are processed within 1-2 business days\n• Custom orders may require additional processing time\n• Processing time excludes weekends and holidays\n• You will receive a confirmation email once your order ships\n\n**Shipping Costs**\n\n• Standard shipping: $15.00\n• Express shipping: $25.00\n• Overnight shipping: $35.00\n• Free shipping on orders over $200\n• International shipping rates vary by destination\n\n**Contact Us**\n\nFor shipping questions or concerns, please contact us at info@pebdeq.com or call +12223334455.",
    "footer_legal_cookie_policy_title": "Cookie Policy",
    "footer_legal_cookie_policy_content": "This Cookie Policy explains how we use cookies and similar technologies when you visit our website.\n\n**What Are Cookies**\n\nCookies are small text files that are placed on your device when you visit our website. They help us provide you with a better browsing experience by remembering your preferences and analyzing site usage.\n\n**Types of Cookies We Use**\n\n**Essential Cookies**\n• Required for the website to function properly\n• Enable core functionality like security and account access\n• Cannot be disabled without affecting site functionality\n\n**Performance Cookies**\n• Collect information about how you use our website\n• Help us improve website performance and user experience\n• Provide analytics about page views and user behavior\n\n**Managing Cookies**\n\nYou can control cookies through your browser settings:\n• Accept all cookies\n• Reject all cookies\n• Receive notifications when cookies are set\n• Delete existing cookies\n\n**Contact Us**\n\nIf you have any questions about our use of cookies, please contact us at info@pebdeq.com.",
    "footer_legal_dmca_notice_title": "DMCA Notice",
    "footer_legal_dmca_notice_content": "We respect intellectual property rights and comply with the Digital Millennium Copyright Act (DMCA).\n\n**Copyright Policy**\n\nWe respect the intellectual property rights of others and expect our users to do the same. We will respond to clear notices of alleged copyright infringement that comply with the DMCA.\n\n**Filing a DMCA Takedown Notice**\n\nIf you believe your copyrighted work has been used on our website without authorization, please provide our designated agent with the following information:\n\n**Required Information**\n• A physical or electronic signature of the copyright owner or authorized agent\n• Identification of the copyrighted work claimed to have been infringed\n• Identification of the material that is claimed to be infringing and location information\n• Your contact information (address, telephone number, and email address)\n• A statement of good faith belief that the use is not authorized\n• A statement that the information is accurate and you are authorized to act on behalf of the copyright owner\n\n**Submission Process**\n\nSend your DMCA notice to our designated agent:\n\n**Email**: dmca@pebdeq.com\n**Phone**: +12223334455\n**Address**: PEBDEQ Legal Department, Virginia, USA\n\n**Contact Our Agent**\n\nFor all DMCA-related communications, please contact our designated agent at dmca@pebdeq.com.",
    "footer_legal_accessibility_statement_title": "Accessibility Statement",
    "footer_legal_accessibility_statement_content": "We are committed to ensuring that our website is accessible to all users, including those with disabilities.\n\n**Our Commitment**\n\nWe strive to make our website accessible to users with disabilities and are committed to providing an inclusive online experience for everyone.\n\n**Accessibility Standards**\n\nWe aim to comply with the Web Content Accessibility Guidelines (WCAG) 2.1 Level AA standards. These guidelines help make web content more accessible to people with disabilities.\n\n**Accessibility Features**\n\nOur website includes the following accessibility features:\n• Alternative text for images\n• Keyboard navigation support\n• Clear heading structure\n• Color contrast optimization\n• Resizable text and zoom functionality\n• Screen reader compatibility\n• Descriptive link text\n• Form labels and instructions\n\n**Feedback and Assistance**\n\nWe welcome feedback about the accessibility of our website. If you encounter any accessibility barriers or need assistance, please contact us:\n\n**Email**: accessibility@pebdeq.com\n**Phone**: +12223334455\n**Mail**: PEBDEQ Accessibility Team, Virginia, USA\n\n**Contact Information**\n\nFor accessibility-related questions, concerns, or assistance, please don't hesitate to contact us. We are here to help ensure you can access all of our content and services."
}

if __name__ == "__main__":
    print("Current Settings Backup loaded successfully!")
    print(f"Total settings: {len(CURRENT_SETTINGS_BACKUP)}") 