"""Add about page CMS fields to SiteSettings

Revision ID: 1a0121271809
Revises: 75b60e302559
Create Date: 2025-07-13 13:40:44.934559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0121271809'
down_revision = '75b60e302559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_page_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_subtitle', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_page_mission_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_mission_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_page_values_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_values_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_page_team_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_team_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_page_history_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_history_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_page_contact_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_page_contact_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_page_show_mission', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('about_page_show_values', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('about_page_show_team', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('about_page_show_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('about_page_show_contact', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('about_page_background_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about_page_background_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('about_page_background_color')
        batch_op.drop_column('about_page_background_image')
        batch_op.drop_column('about_page_show_contact')
        batch_op.drop_column('about_page_show_history')
        batch_op.drop_column('about_page_show_team')
        batch_op.drop_column('about_page_show_values')
        batch_op.drop_column('about_page_show_mission')
        batch_op.drop_column('about_page_contact_content')
        batch_op.drop_column('about_page_contact_title')
        batch_op.drop_column('about_page_history_content')
        batch_op.drop_column('about_page_history_title')
        batch_op.drop_column('about_page_team_content')
        batch_op.drop_column('about_page_team_title')
        batch_op.drop_column('about_page_values_content')
        batch_op.drop_column('about_page_values_title')
        batch_op.drop_column('about_page_mission_content')
        batch_op.drop_column('about_page_mission_title')
        batch_op.drop_column('about_page_content')
        batch_op.drop_column('about_page_subtitle')
        batch_op.drop_column('about_page_title')

    # ### end Alembic commands ###
