"""Add Google OAuth settings to SiteSettings

Revision ID: 44ba9f727e37
Revises: 1a0121271809
Create Date: 2025-07-13 13:50:59.483126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ba9f727e37'
down_revision = '1a0121271809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_oauth_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('google_oauth_client_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('google_oauth_client_secret', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('google_oauth_redirect_uri', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('google_oauth_scope', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('google_oauth_scope')
        batch_op.drop_column('google_oauth_redirect_uri')
        batch_op.drop_column('google_oauth_client_secret')
        batch_op.drop_column('google_oauth_client_id')
        batch_op.drop_column('google_oauth_enabled')

    # ### end Alembic commands ###
