"""add logo shadow settings

Revision ID: 56ab06a42a86
Revises: af51b733fef2
Create Date: 2025-07-13 11:10:04.608093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ab06a42a86'
down_revision = 'af51b733fef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('meta_description')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('products_per_page')
        batch_op.drop_column('show_filters')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('view_count')
        batch_op.drop_column('default_sort')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('last_viewed')
        batch_op.drop_column('is_featured')

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_shadow_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('logo_shadow_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('logo_shadow_blur', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_shadow_offset_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_shadow_offset_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_shadow_opacity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('logo2_shadow_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('logo2_shadow_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('logo2_shadow_blur', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo2_shadow_offset_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo2_shadow_offset_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo2_shadow_opacity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('logo2_shadow_opacity')
        batch_op.drop_column('logo2_shadow_offset_y')
        batch_op.drop_column('logo2_shadow_offset_x')
        batch_op.drop_column('logo2_shadow_blur')
        batch_op.drop_column('logo2_shadow_color')
        batch_op.drop_column('logo2_shadow_enabled')
        batch_op.drop_column('logo_shadow_opacity')
        batch_op.drop_column('logo_shadow_offset_y')
        batch_op.drop_column('logo_shadow_offset_x')
        batch_op.drop_column('logo_shadow_blur')
        batch_op.drop_column('logo_shadow_color')
        batch_op.drop_column('logo_shadow_enabled')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('last_viewed', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('default_sort', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('show_filters', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('products_per_page', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
