"""Add new fields to category table

Revision ID: af51b733fef2
Revises: 9ef6c1f54b25
Create Date: 2025-07-13 01:20:15.411445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af51b733fef2'
down_revision = '9ef6c1f54b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('products_per_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_sort', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('show_filters', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_viewed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_viewed')
        batch_op.drop_column('view_count')
        batch_op.drop_column('show_filters')
        batch_op.drop_column('default_sort')
        batch_op.drop_column('products_per_page')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
